languageCode: 'fr'
baseURL: https://coachbyco.fr
removePathAccents: true

params:
  contact:
    whatsapp:
      content: "06 52 98 42 08"
      prefix: "tel:"
    facebook:
      content: "coachbyco"
      prefix: https://www.facebook.com/
    instagram:
      content: "coach_by_co"
      prefix: https://www.instagram.com/
    email:
      content: coachbyco@gmail.com
      prefix: "mailto:"
  seo:
    author: Coach by Co
    title: Coach by Co - Coach sportif à Bordeaux
    desc: "Coach sportif à Bordeaux, je t'aide à transformer ton corps et atteindre tes objectifs pour te sentir mieux et vivre sans contrainte."
    url: https://coachbyco.fr
    hero: /sprites/hero-min.jpg
    logo: /sprites/logo-min.png
    links:
      facebook: https://www.facebook.com/coachbyco
      instagram: https://www.instagram.com/coach_by_co
      linkedin: https://www.linkedin.com/in/corentin-chevalier-672322253/

taxonomies:

menu:
  main:
    - name: Prestations
      pre: prestations
      url: "/#prestations"
      weight: 2
    - name: À domicile
      pre: tarifs-a-domicile
      url: "/#tarifs-a-domicile"
      weight: 3
    - name: En entreprise
      pre: tarifs-en-entreprise
      url: "/#tarifs-en-entreprise"
      weight: 4
    - name: Contact
      pre: contact
      url: "/#contact"
      weight: 5
