languageCode: 'fr'
title: Coach à Bordeaux
baseURL: https://example.net
removePathAccents: true

params:
  email: coachbyco@gmail.com
  phone: "06 52 98 42 08"
  seo:
    author: Coach by Co
    title: Coach by Co - Coach sportif à Bordeaux
    desc: "Coach sportif à Bordeaux"
    url: https://example.net
    hero: /sprites/hero-min.jpg
    logo: /sprites/logo.png
    links:
      twitter: https://twitter.com/example_account

menu:
  main:
    - name: À propos
      pre: about
      url: "/#about"
      weight: 1
    - name: Prestations
      pre: services
      url: "/#services"
      weight: 2
    - name: Contact
      pre: contact
      url: "/#contact"
      weight: 3
