backend:
  name: git-gateway
  branch: main
local_backend:
  allowed_hosts: ['192.168.1.14', '192.168.198.233']
media_folder: 'static/media'
public_folder: '/media'
locale: fr
slug:
  encoding: ascii
  clean_accents: true

collections:
  - name: services
    label: Prestations
    label_singular: Prestation
    folder: content/services
    create: true
    editor: { preview: false }
    filter: { field: visibleInCms, value: true }
    fields:
      - { label: Visible, name: visibleInCms, widget: hidden, default: true }
      - { label: Brouillon, name: draft, required: false, widget: boolean }
      - { label: Titre,  name: title, required: true }
      - { label: Description, name: body, required: false, widget: markdown, minimal: true, buttons: [bold, link], editor_components: [], modes: [rich_text] }

  - name: testimonies
    label: Témoignages
    label_singular: Témoignage
    folder: content/testimonies
    create: true
    editor: { preview: false }
    filter: { field: visibleInCms, value: true }
    fields:
      - { label: Visible, name: visibleInCms, widget: hidden, default: true }
      - { label: Brouillon, name: draft, required: false, widget: boolean }
      - { label: Ordre,  name: weight, required: true }
      - { label: Nom,  name: title, required: true }
      - { label: Témoignage, name: body, required: false, widget: markdown, minimal: true, buttons: [bold, link], editor_components: [], modes: [rich_text] }
      - { label: Source,  name: source, required: false, hint: "Copiez le lien de partage de l'avis google" }

  - name: sections
    label: Sections
    editor: { preview: false }
    files:
      - label: "Instagram"
        name: "instagram"
        file: "data/sections/instagram.yml"
        fields:
          - { label: "Url publication", name: publication_url, required: true, widget: string }
      - label: "Tarifs"
        name: "pricing"
        file: "data/sections/pricing.yml"
        fields:
          - { label: "Bilan gratuit ?", name: isBilanFree, required: true, widget: boolean }
          - { label: "Tarif bilan (€)", name: bilanPrice, required: true, widget: number, value_type: "float", default: 0 }
          - { label: "Tarif heure (€)", name: hourPrice, required: true, widget: number, value_type: "float", default: 0 }
          - { label: "Durée séance (h)", name: sessionHoursDuration, required: true, widget: number, value_type: "float", default: 1 }
          - { label: "Forfaits", label_singular: "Forfait", name: sessions, widget: list, collapsed: false, summary: 'Forfait {{fields.count}} séances', fields: [
              { label: "Séances/semaine", name: count, required: true, widget: number, value_type: "float", default: 0 },
              { label: "Séances offertes/mois", name: countOffered, required: true, widget: number, value_type: "float", default: 0 },
              { label: "Mis en avant ?", name: isHighlighted, required: true, widget: boolean }
            ] }
          - { label: "Lien bouton \"Demander un bilan\"", name: askResumeLink, required: true, widget: string }
      - label: "Contact"
        name: "contact"
        file: "data/sections/contact.yml"
        fields:
          - { label: "Lien bouton \"Demander un bilan\"", name: askResumeLink, required: true, widget: string }