backend:
  name: git-gateway
  branch: main
local_backend:
  allowed_hosts: ['192.168.1.14']
media_folder: 'static/media'
public_folder: '/media'
locale: fr
slug:
  encoding: ascii
  clean_accents: true

collections:
  - name: services
    label: Prestations
    label_singular: Prestation
    folder: content/services
    create: true
    editor: { preview: false }
    filter: { field: visibleInCms, value: true }
    fields:
      - { label: Visible, name: visibleInCms, widget: hidden, default: true }
      - { label: Titre,  name: title, required: true }
      - { label: Prix, name: prix, required: false, widget: number, value_type: "float", default: 0 }
      - { label: Description, name: description, required: false, widget: markdown, minimal: true, buttons: [bold, link], editor_components: [], modes: [rich_text] }

  - name: sections
    label: Sections
    files:
     - label: "Instagram"
       name: "instagram"
       file: "data/sections/instagram.yml"
       fields:
         - { label: "Url publication", name: publication, required: true, widget: string }
     - label: "Tarifs"
       name: "pricing"
       file: "data/sections/pricing.yml"
       fields:
         - { label: "Bilan gratuit ?", name: isBilanFree, required: true, widget: boolean }
         - { label: "Tarif bilan (€)", name: bilanPrice, required: true, widget: number, value_type: "float", default: 0 }
         - { label: "Tarif heure (€)", name: hourPrice, required: true, widget: number, value_type: "float", default: 0 }
         - { label: "Durée séance (h)", name: sessionHoursDuration, required: true, widget: number, value_type: "float", default: 1 }
         - { label: "Forfaits", label_singular: "Forfait", name: sessions, widget: list, collapsed: false, summary: 'Forfait {{fields.count}} séances', fields: [
             { label: "Séances/semaine", name: count, required: true, widget: number, value_type: "float", default: 0 },
             { label: "Séances offertes/mois", name: countOffered, required: true, widget: number, value_type: "float", default: 0 },
             { label: "Mis en avant ?", name: isHighlighted, required: true, widget: boolean }
           ] }